#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

ensure_dirs
ensure_source_tree
require_device_profile
verify_profile_exists "${DEVICE_PROFILE}" || die "DEVICE_PROFILE was not found in upstream Filogic targets: ${DEVICE_PROFILE}"

if [[ -z "${BASE_DEFCONFIG}" ]]; then
  BASE_DEFCONFIG="$(detect_base_defconfig "${DEVICE_PROFILE}")"
fi

[[ -f "${DEFAULT_SEED}" ]] || die "default seed not found: ${DEFAULT_SEED}"
[[ -f "${BASE_DEFCONFIG}" ]] || die "base defconfig not found: ${BASE_DEFCONFIG}"

mapfile -t seed_files < <(selected_seed_files)
(( ${#seed_files[@]} > 0 )) || die "no seed files found"

config_symbol="CONFIG_TARGET_mediatek_filogic_DEVICE_${DEVICE_PROFILE}"

select_nikki_mihomo_provider

log "generating .config for profile: ${DEVICE_PROFILE}"
log "base defconfig: ${BASE_DEFCONFIG}"
for seed_file in "${seed_files[@]}"; do
  log "seed: ${seed_file}"
done

{
  printf '# Generated by scripts/defconfig.sh. Persistent package defaults live under configs/.\n'
  printf '# Base MediaTek Filogic configuration: %s\n' "${BASE_DEFCONFIG}"
  awk '
    /^CONFIG_TARGET_/ { next }
    /^# CONFIG_TARGET_/ { next }
    /^CONFIG_HAS_SUBTARGETS=/ { next }
    /^# CONFIG_HAS_SUBTARGETS / { next }
    { print }
  ' "${BASE_DEFCONFIG}"
  printf '\n# Device target generated by scripts/defconfig.sh.\n'
  printf 'CONFIG_TARGET_mediatek=y\n'
  printf 'CONFIG_TARGET_mediatek_filogic=y\n'
  printf '%s=y\n' "${config_symbol}"
  printf '\n# Package seed files.\n'
  for seed_file in "${seed_files[@]}"; do
    printf '\n# Seed: %s\n' "${seed_file}"
    cat "${seed_file}"
    printf '\n'
  done
} > "${SOURCE_DIR}/.config"

run_make defconfig

required_symbols=(
  "${config_symbol}"
  CONFIG_PACKAGE_luci
  CONFIG_PACKAGE_luci-app-ttyd
  CONFIG_PACKAGE_luci-theme-argon
  CONFIG_PACKAGE_luci-app-turboacc-mtk
  CONFIG_PACKAGE_kmod-mediatek_hnat
  CONFIG_PACKAGE_kmod-mt_wifi
  CONFIG_PACKAGE_kmod-warp
  CONFIG_PACKAGE_mtwifi-cfg
  CONFIG_PACKAGE_luci-app-nikki
  CONFIG_PACKAGE_luci-app-upnp
  CONFIG_PACKAGE_miniupnpd-nftables
  CONFIG_PACKAGE_kmod-usb-net
  CONFIG_PACKAGE_kmod-usb-net-cdc-ether
  CONFIG_PACKAGE_kmod-usb-net-cdc-ncm
  CONFIG_PACKAGE_kmod-usb-net-rndis
)

for symbol in "${required_symbols[@]}"; do
  require_config_symbol "${symbol}"
done

if [[ -f "${CUSTOM_SEED}" ]]; then
  while IFS= read -r line; do
    if [[ "${line}" =~ ^(CONFIG_PACKAGE_[^=]+)=y$ ]]; then
      require_config_symbol "${BASH_REMATCH[1]}"
    fi
  done < "${CUSTOM_SEED}"
fi

log "defconfig complete"
