#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

ensure_source_tree

mkdir -p "$(dirname -- "${CUSTOM_SEED}")"

printf 'Scanning packages from source/package and source/feeds...\n'
mapfile -t packages < <("${SCRIPT_DIR}/list-packages.sh")
(( ${#packages[@]} > 0 )) || die "no packages found. Run initialization first"

declare -A selected=()
if [[ -f "${CUSTOM_SEED}" ]]; then
  while IFS= read -r line; do
    if [[ "${line}" =~ ^CONFIG_PACKAGE_([^=]+)=y$ ]]; then
      selected["${BASH_REMATCH[1]}"]=1
    fi
  done < "${CUSTOM_SEED}"
fi

filter=""
max_rows=80

selected_count() {
  local count=0
  local key
  for key in "${!selected[@]}"; do
    [[ "${selected[$key]}" == "1" ]] && count=$((count + 1))
  done
  printf '%d\n' "${count}"
}

save_selection() {
  {
    printf '# Generated by scripts/select-packages.sh.\n'
    printf '# Leave empty to use only configs/default.seed and device-specific seed files.\n'
    printf '\n'
    for pkg in "${!selected[@]}"; do
      [[ "${selected[$pkg]}" == "1" ]] && printf '%s\n' "${pkg}"
    done | sort | while IFS= read -r pkg; do
      printf 'CONFIG_PACKAGE_%s=y\n' "${pkg}"
    done
  } > "${CUSTOM_SEED}"
  printf 'Saved optional package seed: %s\n' "${CUSTOM_SEED}"
}

while true; do
  printf '\nOptional firmware packages\n'
  printf 'Selected: %s\n' "$(selected_count)"
  if [[ -n "${filter}" ]]; then
    printf 'Filter: %s\n' "${filter}"
  fi
  printf '\n'

  visible=()
  filter_lower="${filter,,}"
  for pkg in "${packages[@]}"; do
    haystack="${pkg,,}"
    if [[ -z "${filter_lower}" || "${haystack}" == *"${filter_lower}"* ]]; then
      visible+=("${pkg}")
    fi
  done

  if (( ${#visible[@]} == 0 )); then
    printf 'No matches. Use /keyword to search again, a to show all, s to save, q to return.\n'
  else
    shown="${#visible[@]}"
    (( shown > max_rows )) && shown="${max_rows}"
    for ((i = 0; i < shown; i++)); do
      pkg="${visible[i]}"
      mark="[ ]"
      [[ "${selected[$pkg]:-0}" == "1" ]] && mark="[*]"
      printf '%4d. %s %s\n' "$((i + 1))" "${mark}" "${pkg}"
    done
    if (( ${#visible[@]} > max_rows )); then
      printf '... showing %d of %d matches. Search to narrow the list.\n' "${max_rows}" "${#visible[@]}"
    fi
  fi

  printf '\n'
  read -r -p 'Number toggle, /keyword search, a all, c clear, s save, q return: ' input

  case "${input}" in
    q|Q)
      exit 0
      ;;
    s|S)
      save_selection
      exit 0
      ;;
    a|A|"")
      filter=""
      continue
      ;;
    c|C)
      selected=()
      continue
      ;;
    /*)
      filter="${input#/}"
      continue
      ;;
  esac

  for token in ${input}; do
    if [[ ! "${token}" =~ ^[0-9]+$ ]]; then
      printf 'Invalid input: %s\n' "${token}" >&2
      continue
    fi

    index=$((token - 1))
    if (( index < 0 || index >= ${#visible[@]} || index >= max_rows )); then
      printf 'Selection out of range: %s\n' "${token}" >&2
      continue
    fi

    pkg="${visible[index]}"
    if [[ "${selected[$pkg]:-0}" == "1" ]]; then
      selected["${pkg}"]=0
    else
      selected["${pkg}"]=1
    fi
  done
done
