#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

ensure_dirs
ensure_source_tree
[[ -f "${CONFIG_SEED}" ]] || die "config seed not found: ${CONFIG_SEED}"

profile="$(detect_device_profile)"
config_symbol="CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_${profile}"

log "generating .config for profile: ${profile}"
{
  printf '# Generated by scripts/defconfig.sh. Edit configs/cudy_tr3000_128m.seed for persistent package changes.\n'
  printf 'CONFIG_TARGET_mediatek=y\n'
  printf 'CONFIG_TARGET_mediatek_filogic=y\n'
  printf '%s=y\n' "${config_symbol}"
  cat "${CONFIG_SEED}"
} > "${SOURCE_DIR}/.config"

run_make defconfig

required_symbols=(
  "${config_symbol}"
  CONFIG_PACKAGE_luci
  CONFIG_PACKAGE_luci-app-ttyd
  CONFIG_PACKAGE_luci-theme-argon
  CONFIG_PACKAGE_luci-app-turboacc-mtk
  CONFIG_PACKAGE_luci-app-nikki
  CONFIG_PACKAGE_luci-app-upnp
  CONFIG_PACKAGE_miniupnpd
  CONFIG_PACKAGE_luci-app-advanced-reboot
  CONFIG_PACKAGE_kmod-usb-net
  CONFIG_PACKAGE_kmod-usb-net-cdc-ether
  CONFIG_PACKAGE_kmod-usb-net-cdc-ncm
  CONFIG_PACKAGE_kmod-usb-net-rndis
)

for symbol in "${required_symbols[@]}"; do
  require_config_symbol "${symbol}"
done

log "defconfig complete"
