#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

ensure_dirs
ensure_source_tree
[[ -f "${CONFIG_SEED}" ]] || die "config seed not found: ${CONFIG_SEED}"
[[ -f "${BASE_DEFCONFIG}" ]] || die "base defconfig not found: ${BASE_DEFCONFIG}"

profile="$(detect_device_profile)"
config_symbol="CONFIG_TARGET_mediatek_filogic_DEVICE_${profile}"

select_nikki_mihomo_provider

log "generating .config for profile: ${profile}"
{
  printf '# Generated by scripts/defconfig.sh. Edit configs/cudy_tr3000_128m.seed for persistent package changes.\n'
  printf '# Base MT7981 vendor-driver configuration: %s\n' "${BASE_DEFCONFIG}"
  awk '
    /^CONFIG_TARGET_/ { next }
    /^# CONFIG_TARGET_/ { next }
    /^CONFIG_HAS_SUBTARGETS=/ { next }
    /^# CONFIG_HAS_SUBTARGETS / { next }
    { print }
  ' "${BASE_DEFCONFIG}"
  printf '\n# Device target generated by scripts/defconfig.sh.\n'
  printf 'CONFIG_TARGET_mediatek=y\n'
  printf 'CONFIG_TARGET_mediatek_filogic=y\n'
  printf '%s=y\n' "${config_symbol}"
  printf '\n# Project-specific package overlay.\n'
  cat "${CONFIG_SEED}"
} > "${SOURCE_DIR}/.config"

run_make defconfig

required_symbols=(
  "${config_symbol}"
  CONFIG_PACKAGE_luci
  CONFIG_PACKAGE_luci-app-ttyd
  CONFIG_PACKAGE_luci-theme-argon
  CONFIG_PACKAGE_luci-app-turboacc-mtk
  CONFIG_PACKAGE_kmod-mediatek_hnat
  CONFIG_PACKAGE_kmod-mt_wifi
  CONFIG_PACKAGE_kmod-warp
  CONFIG_PACKAGE_mtwifi-cfg
  CONFIG_PACKAGE_luci-app-nikki
  CONFIG_PACKAGE_luci-app-upnp
  CONFIG_PACKAGE_miniupnpd-nftables
  CONFIG_PACKAGE_luci-app-advanced-reboot
  CONFIG_PACKAGE_kmod-usb-net
  CONFIG_PACKAGE_kmod-usb-net-cdc-ether
  CONFIG_PACKAGE_kmod-usb-net-cdc-ncm
  CONFIG_PACKAGE_kmod-usb-net-rndis
)

for symbol in "${required_symbols[@]}"; do
  require_config_symbol "${symbol}"
done

log "defconfig complete"
